version: '3.7'
services:
  dev:
    container_name: helper-partial-benchmark
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "/app/start.sh"]
    ports:
      - 8080:3000
    volumes:
      - .:/app
    stdin_open: true
    tty: true
